name: Build

on:
  push:
    branches:
      - "master"
      
jobs:
          
  buildwindows:
    name: Windows x64
    runs-on: windows-2019

    steps: 
      - name: setup em
        uses: lovasoa/setup-emscripten@master
        with:
          emscripten-version: '2.0.14'     
      - name: Prepare Qt Libraries
        uses: jurplel/install-qt-action@v3
        with:
           version: '6.2.*'
     
      - name: Clone
        uses: actions/checkout@v3
      
      - name: Compile
        shell: cmd
        run: | 
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

          qmake CONFIG+=release dashmaster.pro
          nmake /C

      - name: Package
        run: |
          em++ --version
          dir
          dir build

      - uses: actions/upload-artifact@v4
        with:
          name: SavvyCAN-Windows_x64
          path: package
 

          
